### ISSUE TITLE
Missing dependency on laminas-http

### ISSUE THREAD

**Issue by devicenull** [laminas/laminas-session#38]
### Bug Report

We started trying to use laminas-session in an app that's not using any other laminas components, and hit an error:

Fatal error: Uncaught Error: Class 'Laminas\Http\PhpEnvironment\RemoteAddress' not found in vendor/laminas/laminas-session/src/Validator/RemoteAddr.php on line 127

It seems this class is provided by laminas-http, however this package is not marked as a dependency of laminas-session

**Comment by froschdesign** [comment]
> however this package is not marked as a dependency of laminas-session

Right, it is listed as [suggested package](https://getcomposer.org/doc/04-schema.md#suggest) because it is only needed for [RemoteAddr validator](https://docs.laminas.dev/laminas-session/validator/#remote-addr) and therefore a _soft_ dependency.

But this information is missing in the documentation.
